### ISSUE TITLE
How do I cancel a completion?

### ISSUE THREAD

**Issue by alienbogart** [schasse/tmux-jump#10]
It is not clear if there's a way to leave the char mode with a single command.

**Comment by schasse** [comment]
Hey,
it's possible to cancel the char mode with chars that are not used for the selection, e.g. `q`.
Does that solve your problem?
If you want you can create a PR that adjusts the README.md.

**Comment by schasse** [comment]
Improved behavior, when hitting <kbd>CTRL</kbd>+<kbd>c</kbd>. https://github.com/schasse/tmux-easymotion/commit/a399350a986d10ad794b7d50f60f7f88f3bcfcd2 (currently on beta branch)

**Comment by schasse** [comment]
merged to master
