### ISSUE TITLE
enable plugin when already in copy mode and scrolled around

### ISSUE THREAD

**Issue by Lgggg** [schasse/tmux-jump#11]
please help~

**Comment by Lgggg** [comment]
it jump to the bottom when wake up this plugin

**Comment by schasse** [comment]
Hey, this is currently not possible. I keep this on the todo list.

**Comment by Lgggg** [comment]
thank~ I like your plugin very much~

**Comment by schasse** [comment]
duplicate of https://github.com/schasse/tmux-easymotion/issues/4
