### ISSUE TITLE
Make it possible to customize tmux key, right now it's hard coded to j.

### ISSUE THREAD

**Issue by 123subhadeep** [schasse/tmux-jump#18]
Right now the tmux key to start the jump is hard coded to j : https://github.com/schasse/tmux-jump/blob/master/tmux-jump.tmux#L4

I have j mapped to some other action in tmux.
I worked around it by modifying the source code, but it will be great to have that customizable.

**Comment by schasse** [comment]
Thanks for the contribution, @dianlujitao!
