### ISSUE TITLE
Addition: jump in copy-mode

### ISSUE THREAD

**Issue by zenhog** [schasse/tmux-jump#22]
Hi,

It seems you can't jump when you're already in copy-mode, which could be a nice addition, as this would allow text-selection.

**Comment by schasse** [comment]
Hey @zenfailure,

Thanks for your remark. Nevertheless, using jump during copy mode should be possible. I added this feature a while ago https://github.com/schasse/tmux-jump/pull/16/files Could you make sure that you are using the latest version.

In case this doesn't help. Maybe you found a bug. In this case which OS do you use and could you elaborate on how to reproduce the problem.

Cheers

**Comment by schasse** [comment]
I'll close this cause it's already implemented.
