### ISSUE TITLE
Error 127 after using key binding

### ISSUE THREAD

**Issue by SMMousaviSP** [schasse/tmux-jump#23]
This is the output when I use tmux-prefix + j:
```
'/home/mohammad/.tmux/plugins/tmux-jump/scripts/tmux-jump.sh' returned 127
```
I can run tmux-jump.sh directly without problem but not with the key binding.

OS: Ubuntu 20.4
tmux version: 3.0a
Ruby version: 2.7.1p83

**Comment by schasse** [comment]
Hi,

thanks for reporting this.

Exit code 127 indicates command not found. And probably it's ruby. How did you install ruby? Is it available just in your current shell or is it globally available? What does `which ruby` return? And what does `echo $PATH` return?

**Comment by SMMousaviSP** [comment]
Hi,

I've installed latest stable version of ruby with rbenv.

This is the output of `which ruby`:
```
/home/mohammad/.rbenv/shims/ruby
```
And `/home/mohammad/.rbenv/shims` is in my path.
echo $PATH output:
```
/home/mohammad/.rbenv/shims:/home/mohammad/.rbenv/bin:/home/mohammad/.pyenv/plugins/pyenv-virtualenv/shims:/home/mohammad/.pyenv/shims:/home/mohammad/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by schasse** [comment]
Okay. When tmux starts a shell, the setup of the environment is probably different and it doesn‘t setup the path. 

There are different options to solve this:
* installing ruby globally
* patching tmux-jump.sh to use your local ruby version
* create a symlink in a global bin path (like /usr/local/bin) pointing to your local ruby version

I‘d recommend installing ruby globally. I‘m don‘t know, though, how that‘s done easily with mac. This allows you to update tmux-jump in the future without having to resolve conflicts.

**Comment by SMMousaviSP** [comment]
Problem solved by installing ruby from ubuntu repository:
```
sudo apt install ruby
```
Thank you
