### ISSUE TITLE
Screen rerenders inconsistently

### ISSUE THREAD

**Issue by roy2220** [schasse/tmux-jump#29]
a) Most of the time my screen renders like this (normal):

<img width="1280" alt="2" src="https://user-images.githubusercontent.com/6377788/98058902-ca15b700-1e80-11eb-8c9b-046bc1ac406d.png">

b) And sometimes (broken):

<img width="1280" alt="1" src="https://user-images.githubusercontent.com/6377788/98059037-1bbe4180-1e81-11eb-9639-a1be3596e433.png">

**Situation `b` is likely to happen when works with Vim.** I am using this color scheme: [gruvbox8](https://github.com/lifepillar/vim-gruvbox8)

**Comment by schasse** [comment]
Hey @roy2220,

thanks for the Feedback. I see the same issue when using it in emacs. I think that it has to do the fact that tmux doesn't return whitespace in [this](https://github.com/schasse/tmux-jump/blob/master/scripts/tmux-jump.rb#L62) command. I don't have good idea, though, on how to fix it...
Any ideas?

**Comment by roy2220** [comment]
> Hey @roy2220,
> 
> thanks for the Feedback. I see the same issue when using it in emacs. I think that it has to do the fact that tmux doesn't return whitespace in [this](https://github.com/schasse/tmux-jump/blob/master/scripts/tmux-jump.rb#L62) command. I don't have good idea, though, on how to fix it...
> Any ideas?

I found something helpful from tmux's manual
>     capture-pane [-aepPqCJN] [-b buffer-name] [-E end-line] [-S start-line]
>             [-t target-pane]
>                   (alias: capturep)
>             Capture the contents of a pane.  If -p is given, the output
>             goes to stdout, otherwise to the buffer specified with -b or a
>             new buffer if omitted.  If -a is given, the alternate screen is
>             used, and the history is not accessible.  If no alternate
>             screen exists, an error will be returned unless -q is given.
>             If -e is given, the output includes escape sequences for text
>             and background attributes.  -C also escapes non-printable char‐
>             acters as octal \xxx.  -N preserves trailing spaces at each
>             line's end and -J preserves trailing spaces and joins any
>             wrapped lines.  -P captures only any output that the pane has
>             received that is the beginning of an as-yet incomplete escape
>             sequence.

The `-N` and `-J`!

I have tried editing `tmux-jump.rb`, adding option `-J` to every `tmux capture-pane`, and then the rendering problem seems solved! Unfortunately, another problem arose: can't  jump to the position corresponding to the key pressed accurately. I think more changes to the code is required to make everything work fine, but I'm a 'moron' of Ruby, would you like to help?

**Comment by roy2220** [comment]
@schasse Finally, I fixed it on my own. I didn't introduce any additional command-line option of `tmux capture-pane`, just extend lines captured as long as the width of the pane with whitespaces, for the compatibility with earlier versions of Tmux. Give it a review please! => #30

**Comment by schasse** [comment]
Hey @roy2220, 
that's awesome! On the first sight the PR looks good to me. I'll test your changes a bit locally on my computer and give you feedback.

**Comment by roy2220** [comment]
@schasse I'm sorry to say that I have partially reimplemented tmux-jump in Python for my own personal use => https://github.com/roy2220/easyjump.tmux 😂, so I'm not going to continue working on this issue. Anyway, thanks for your help and your awesome project, which inspired me indeed.

**Comment by schasse** [comment]
Hey @roy2220, yeah pretty cool. I think it's a fun project to implement and not difficult. I'm happy if anybody can profit from it, also as source of inspiration.

**Comment by inzeets** [comment]
JFYI, redrawing the screen with `ctrl-l` before doing the jump fixed this for me.
Leaving it here to help someone looking for the quick fix:
`bind-key j send-keys C-l \; run-shell "~/.tmux/plugins/tmux-jump/scripts/tmux-jump.sh"`
The idea behind this plugin and similar implementations is rocking at fzf and gpt level of productivity boost.
