### ISSUE TITLE
not all results are highlighted

### ISSUE THREAD

**Issue by Karmenzind** [schasse/tmux-jump#36]
I searched `i`:

![image](https://user-images.githubusercontent.com/17923071/198577001-006f10ad-3c50-47e0-bf54-8a3b7ffaeca5.png)

**Comment by schasse** [comment]
Hey Karmenzind,

tmux-jump searches only for the first character of a word.

Does that answer your request?

**Comment by Karmenzind** [comment]
Yes it does. Thanks.
