### ISSUE TITLE
How to use tmux-jump to copy text?

### ISSUE THREAD

**Issue by Liquidmantis** [schasse/tmux-jump#37]
I haven't figured this out and haven't been able to pull this nugget out of the animated gif.  I can jump fine but can't seem to copy or yank.  Help, please!  :)

**Comment by eggbean** [comment]
If you are sure it's installed correctly and you haven't changed the keybinding, `prefix`+`j` then type the first character in of the word you want to jump to in the tmux window. Then every word that starts with that letter you typed will be highlighted with a couple of characters in red. Type those two characters of the place where you want to jump to in tmux copy-mode.

Then you use copy-mode as usual. It's for quickly jumping to locations in copy-mode, not for actually copying (yanking).

**Comment by schasse** [comment]
Thanks @eggbean, perfectly explained!

@Liquidmantis, I usually combine my plugin with tmux-yank, it can paste the selection directly to the command line.

https://github.com/tmux-plugins/tmux-yank

**Comment by Liquidmantis** [comment]
> Then you use copy-mode as usual. It's for quickly jumping to locations in copy-mode, not for actually copying (yanking).

That's what I was missing.  The animated gif had me confused as to how `this one` was copied.  

So the workflow then would be:
- `prefix + j` to enter jump mode
- type character and jump to beginning of target word (which enters copy mode)
- press `space` to enter selection mode
- use typical movements to extend selection to encompass text
- press `return` to capture and exit copy mode

**Comment by eggbean** [comment]
I didn't realise you could also press `Enter`. I usually type `y` to yank and the `q` to quit. While selecting you can also press `v` to make block selections.

`return`? I think it said that on my Commodore 64. That's an old typewriter phrase.

**Comment by Liquidmantis** [comment]
@eggbean Are you calling me old?  😆
