### ISSUE TITLE
`bind-key -N` broken for older tmux versions 

### ISSUE THREAD

**Issue by dshahbaz** [schasse/tmux-jump#38]
According to https://raw.githubusercontent.com/tmux/tmux/3.3a/CHANGES `bind-key -N ...` was added with tmux 3.1.

The stated required version for tmux-jump is  1.8. However, this recent change https://github.com/schasse/tmux-jump/commit/7341dba4b5f11c2161788cef38f063c375f023d1 breaks 1.8 (actually, anything <3.1) support.

**Comment by eggbean** [comment]
Yeah, that was my PR. I didn't notice that the readme said that. tmux 3.1 came out over three years ago now, so I didn't think it was likely that somebody using a plugin like this would still be using such an old version. Have you got tmux from the RHEL repository or something?

You make a single statically-linked binary using this: https://github.com/mjakob-gh/build-static-tmux

**Comment by dshahbaz** [comment]
i'm on an older ubuntu, i can probably install via snap or something.

can probably resolve this by updating the `README` then.
