### ISSUE TITLE
127 return error: Command not found?

### ISSUE THREAD

**Issue by ekr990011** [schasse/tmux-jump#40]
I just installed the plugin via tpm when attempting to use it I receive this:
`'/home/doom/.tmux/plugins/tmux-jump/scripts/tmux-jump.sh'  returned 127`

When I run that script in tmux in another pane it works as intended.

When i remove it from tpm and use it locally with putting the script path in .tmux.conf it also fails.
When i reload my .tmux.conf it shows me that error.

I am using zsh, I have ruby installed via rvm.

Any direction would be much appreciated.

EDIT:
I didn't have my shell logged in. Not sure why this mattered as the ruby command was working.

**Comment by schasse** [comment]
Hey ekr990011,
Sounds like the RVM setup might have some problems. I know that a login shell sources different files than a non-login shell. And it depends on what rvm depends on `.profile`, `.bash-profile`, `.bashrc`. In any case, I'm glad that your problem has been solved for now.
