### ISSUE TITLE
Jump to char does not work

### ISSUE THREAD

**Issue by oemergenc** [schasse/tmux-jump#6]
Hi,

thanks for this plugin. I was search a long time for this. Unfortuneately the easymotion does not work on my machine. After the pressing **PREFIX + j** i can see the **char:** prompt. However after pressing a character i got the following error message:

```
'printf d >> /proc/38557/fd/8' returned 1
```

Any idea?

**Comment by schasse** [comment]
Hi oemergenc,

I see, `returned 1` indicates that the `printf d >> /proc/38557/fd/8` command fails. It's being used for sending the typed character from the tmux process to the ruby script.
Which os and version of os do you use?
Please check `printf` is available and that there are folders like this on your filesystem `/proc/<some process id>`.

**Comment by oemergenc** [comment]
Hey,

i am on Mac OS X Mojave. Maybe this is the problem, because there are no /proc/... directories in OS X. The `printf` function seems to be working just fine. Is there any way to get this plugin also working on OS X?

**Comment by schasse** [comment]
sure, either ruby has a generic interface for posix compatible os, or we'll implement a mac os specific version. I'll do a research of how we can achieve this.

**Comment by schasse** [comment]
I've created an implementation that should work for Mac OS as well https://github.com/schasse/tmux-easymotion/pull/7
Could you test it and give me feedback if it works? You need to install the plugin manually, though:

```
cd $HOME
git clone --branch fix_mac_os git@github.com:schasse/tmux-easymotion.git
```
```
### in tmux.conf
# set -g @plugin 'schasse/tmux-easymotion' # (needs to be disabled, e.g. via comment)
run '$HOME/tmux-easymotion/easymotion.tmux'
```

**Comment by oemergenc** [comment]
Wow, thank you very much. That was fast. Works like a charm.

See this. I will definitely have a look at the code to see how you have done it. 

![easymotion](https://user-images.githubusercontent.com/10146674/67702298-c7e96480-f9b1-11e9-8652-584ec222e273.gif)

**Comment by schasse** [comment]
sure, no problem. I merged the fix to master, so you can go back to the standard installation if you like.
